
services:
  web:
    image: nginx:latest
    ports:
      - "9090:80"
    networks:
      - my_network

  app:
    image: alpine
    command: sleep infinity
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
