# Generated by Django 4.1 on 2025-04-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0006_address_author_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("code", models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="publish_country",
            field=models.ManyToManyField(to="book_outlet.country"),
        ),
    ]
