# Generated by Django 4.1 on 2025-04-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0007_country_book_publish_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="publish_country",
            new_name="published_countries",
        ),
    ]
