# Generated by Django 4.1 on 2025-04-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0008_rename_publish_country_book_published_countries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["name"],
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.AlterUniqueTogether(
            name="country",
            unique_together={("name", "code")},
        ),
        migrations.AlterModelTable(
            name="country",
            table="country",
        ),
    ]
