# Generated by Django 4.1 on 2025-04-22 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "book_outlet",
            "0009_alter_country_options_alter_country_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["city", "street"],
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "Authors"},
        ),
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={("street", "postal_code", "city")},
        ),
        migrations.AlterModelTable(
            name="address",
            table="address",
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("excerpt", models.CharField(max_length=200)),
                ("image_name", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MinValueValidator(10)]
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="book_outlet.country",
                    ),
                ),
                ("tags", models.ManyToManyField(to="book_outlet.tag")),
            ],
            options={
                "verbose_name_plural": "Posts",
            },
        ),
    ]
